### PR TITLE
Limit compulsory objects in DataSet dims/data_vars/attrs/coords

### PR DESCRIPTION
**Pull request by lucduron**
Try to consider #13 with 2 main modifications:
* distinguish DataSet content for 2D and 3D (the dimension plan is only available in 3D)
* attributes are now optional and not redondant

Tests were completed.

### CODE REVIEW

**Comment by lucduron** [comment]
@tomsail : could you please try and tell if the performance and the new DataSet is OK for you?

Minor improvments are still necessary (to be able to add a new variable, read French variable names...), I could be done in a new PR.

**Comment by lucduron** [comment]
Should ikle2, ikle3 shift to compulsory **attributes** (and not **coords**)?
Indeed I think they add some useless dimensions (elem2, ndp2, elem3, ndp3).

**Comment by tomsail** [comment]
Thanks. I'll do a check on a big file

**Comment by tomsail** [comment]
123seconds on a vector selection on a 3M points mesh of 32GB (3 paramters) and extracted: 
```
<xarray.Dataset> Size: 26MB
Dimensions:    (time: 745, seaset_id: 4410)
Coordinates:
  * time       (time) datetime64[ns] 6kB 2023-07-01 ... 2023-08-01
  * seaset_id  (seaset_id) int64 35kB 0 1 2 4 5 6 ... 6111 6112 6113 6114 6115
    lon        (seaset_id) float32 18kB 13.56 13.24 12.12 ... 3.163 3.2 17.1
    lat        (seaset_id) float32 18kB -12.33 -8.787 -15.19 ... 51.35 57.37
Data variables:
```
the performance is impressive :) I won't complain

> Should ikle2, ikle3 shift to compulsory **attributes** (and not **coords**)? Indeed I think they add some useless dimensions (elem2, ndp2, elem3, ndp3).

they do add useless dimensions. 
I see you've put ikle2 and ikle3 in compulsory variable

It looks good to me. 
It's true that in 2D user has to specify both, and it is overkill in 2D because we have ikle2 = ikle3. 

It might be worth it to not put ikle3 compulsory in 2D. But if adds complexity, or worse if it looses clarity, let's keep it like this. 

Let me know what you think. 

Awesome job

**Comment by lucduron** [comment]
I just shifted `ikle2` and `ikle3` from coordinates to attributes (it removes useless dimensions).
`ikle3` is optional, even in 3D.

**Comment by lucduron** [comment]
I just did some more commits to enable new feature around variable and date_start.

@tomsail: Can you have a look and terminate PR if you are OK. This should then be a new version in PyPI.

**Review by tomsail — APPROVED** [review]

**Pull request merged**
